git hook isntalation

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -1,4 +1,16 @@
 #!/bin/sh
 
-# run the tests with the gradle wrapper
-./gradlew test
+echo "Running static analysis..."
+
+# Inspect code using Detekt
+./gradlew ktlint --daemon
+
+status=$?
+
+if [ "$status" = 0 ] ; then
+    echo "Static analysis found no problems."
+    exit 0
+else
+    echo 1>&2 "Static analysis found violations it could not fix."
+    exit 1
+fi
